name: Auto Merge

on:
  pull_request_target:
    types: [labeled, unlabeled, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: ${{ vars.AUTO_MERGE_METHOD || 'squash' }}
