name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract user request
        id: extract-request
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            COMMENT_BODY='${{ github.event.comment.body }}'
            ISSUE_NUMBER=${{ github.event.issue.number }}
          elif [ "${{ github.event_name }}" == "pull_request_review_comment" ]; then
            COMMENT_BODY='${{ github.event.comment.body }}'
            ISSUE_NUMBER=${{ github.event.pull_request.number }}
          elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
            COMMENT_BODY='${{ github.event.review.body }}'
            ISSUE_NUMBER=${{ github.event.pull_request.number }}
          else
            COMMENT_BODY='${{ github.event.issue.body }}'
            ISSUE_NUMBER=${{ github.event.issue.number }}
          fi

          # @claude以降のテキストを抽出
          REQUEST=$(echo "$COMMENT_BODY" | sed -n 's/.*@claude\s*\(.*\)/\1/p')
          echo "request=$REQUEST" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Get PR diff if applicable
        id: get-diff
        run: |
          if [ "${{ github.event.pull_request.number }}" != "" ]; then
            DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}..HEAD)
            echo "diff<<EOF" >> $GITHUB_OUTPUT
            echo "$DIFF" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Call Claude API
        id: claude-response
        run: |
          USER_REQUEST='${{ steps.extract-request.outputs.request }}'
          DIFF='${{ steps.get-diff.outputs.diff }}'

          if [ -n "$DIFF" ]; then
            PROMPT="ユーザーのリクエスト: $USER_REQUEST\n\nPRの変更内容:\n\`\`\`diff\n$DIFF\n\`\`\`\n\n上記を踏まえて日本語で回答してください。"
          else
            PROMPT="ユーザーのリクエスト: $USER_REQUEST\n\n日本語で回答してください。"
          fi

          RESPONSE=$(curl -s -X POST https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -d '{
              "model": "claude-3-5-sonnet-20241022",
              "max_tokens": 1000,
              "messages": [{
                "role": "user",
                "content": "'"$PROMPT"'"
              }]
            }')

          CLAUDE_REPLY=$(echo "$RESPONSE" | jq -r '.content[0].text')
          echo "reply<<EOF" >> $GITHUB_OUTPUT
          echo "$CLAUDE_REPLY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Claude response
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.extract-request.outputs.issue_number }}/comments" \
            -d "{\"body\":\"🤖 **Claude**: ${{ steps.claude-response.outputs.reply }}\"}"
