name: Claude Assistant

on:
  issue_comment:
    types: [created]

jobs:
  claude-assistant:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract user request
        id: extract-request
        run: |
          COMMENT_BODY='${{ github.event.comment.body }}'
          # @claude以降のテキストを抽出
          REQUEST=$(echo "$COMMENT_BODY" | sed -n 's/.*@claude\s*\(.*\)/\1/p')
          echo "request=$REQUEST" >> $GITHUB_OUTPUT

      - name: Get PR context
        id: get-context
        run: |
          PR_NUMBER=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
          PR_DATA=$(gh pr view $PR_NUMBER --json title,body,baseRefName)
          PR_TITLE=$(echo "$PR_DATA" | jq -r .title)
          PR_BODY=$(echo "$PR_DATA" | jq -r .body)
          BASE_REF=$(echo "$PR_DATA" | jq -r .baseRefName)
          DIFF=$(git diff origin/$BASE_REF..HEAD)

          echo "pr_title<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call Claude API
        id: claude-response
        env:
          CLAUDE_MODEL_NAME: ${{ vars.CLAUDE_MODEL_NAME || 'claude-3-5-sonnet-20240620' }}
        run: |
          USER_REQUEST='${{ steps.extract-request.outputs.request }}'
          PR_TITLE='${{ steps.get-context.outputs.pr_title }}'
          PR_BODY='${{ steps.get-context.outputs.pr_body }}'
          DIFF='${{ steps.get-context.outputs.diff }}'

          # プロジェクトのルールとPRの文脈を組み込んだプロンプトを生成
          PROMPT="あなたはPythonエキスパートのペアプログラマーです。このプロジェクトはPoetry, Python 3.12+, Ruff, pytestを使用し、全てのコードはsrc/に配置されます。\n\n以下のPR情報とユーザーの質問に基づき、具体的かつ的確な回答を日本語で生成してください。\n\n**PRタイトル:** $PR_TITLE\n**PR本文:**\n$PR_BODY\n\n**ユーザーの質問:** $USER_REQUEST\n\n**関連するコードの差分:**\n\`\`\`diff\n$DIFF\n\`\`\`"

          # 安全な方法でAPIリクエストのJSONをファイルに書き出す
          jq -n \
            --arg model "$CLAUDE_MODEL_NAME" \
            --arg content "$PROMPT" \
            '{model: $model, max_tokens: 4096, messages: [{"role": "user", "content": $content}]}' > request.json

          # Claude APIに送信し、レスポンスとHTTPステータスコードを取得
          RESPONSE_DATA=$(curl -s -w "\n%{http_code}" -X POST https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            --data-binary @request.json)

          HTTP_CODE=$(echo "$RESPONSE_DATA" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE_DATA" | sed '$d')

          # エラーハンドリング
          if [ "$HTTP_CODE" -ne 200 ]; then
            CLAUDE_REPLY="Claude APIとの通信に失敗しました (HTTP Status: $HTTP_CODE)。\n\n\`\`\`\n$RESPONSE_BODY\n\`\`\`"
          else
            CLAUDE_REPLY=$(echo "$RESPONSE_BODY" | jq -r '.content[0].text')
          fi

          echo "reply<<EOF" >> $GITHUB_OUTPUT
          echo "$CLAUDE_REPLY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Claude response
        run: |
          PR_NUMBER=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
          # 安全な方法でPRコメントのJSONをファイルに書き出す
          jq -n --arg body "🤖 **Claude Assistant**\n\n${{ steps.claude-response.outputs.reply }}" '{body: $body}' > comment.json

          gh pr comment $PR_NUMBER --body-file comment.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
