name: Assign next queued step
on:
  pull_request:
    types: [closed]          # PR が closed（＝Merged / Closed）されたら発火

jobs:
  next:
    if: github.event.pull_request.merged == true   # Merged のみ対象
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) キュー（step,queued ラベル付き）の最上位 Issue を取得
      - name: Pick next queued Issue
        id: next
        run: |
          ISSUE=$(gh issue list \
                  --label step,queued \
                  --state open \
                  --sort created \
                  --json number \
                  -q '.[0].number')
          echo "issue=$ISSUE" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2) Copilot Agent にアサインし、ラベルを更新
      - name: Assign Copilot & move label
        if: steps.next.outputs.issue != ''
        run: |
          gh issue edit "${{ steps.next.outputs.issue }}" \
            --add-assignee github-copilot \
            --remove-label queued \
            --add-label in-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
